import type { Metadata } from "next";
import { Geist, Geist_Mono ,Roboto} from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
const roboto = Roboto({
  weight: ['400', '700'], // Specify the weights you need
  subsets: ['latin'],    // Specify the subsets you need
  display: 'swap',       // Ensures the fallback font is used while roboto loads
});
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={roboto.className}>
      <body
      className={roboto.className}
      >
        <Header></Header>
        {children}
      </body>
    </html>
  );
}
